import { c as create_ssr_component, e as escape, d as add_attribute } from "../../../chunks/ssr.js";
import { S as SITE_URL, a as SITE_TITLE, D as DEFAULT_OG_IMAGE } from "../../../chunks/siteConfig.js";
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { data } = $$props;
  if ($$props.data === void 0 && $$bindings.data && data !== void 0)
    $$bindings.data(data);
  data.items;
  return `${$$result.head += `<!-- HEAD_svelte-286kb8_START -->${$$result.title = `<title>${escape(SITE_TITLE)} - Contact Us</title>`, ""}<link rel="canonical"${add_attribute("href", `${SITE_URL}/contact`, 0)}><meta property="og:url"${add_attribute("content", `${SITE_URL}/contact`, 0)}><meta property="og:type" content="article"><meta property="og:title"${add_attribute("content", `${SITE_TITLE} - Contact Us`, 0)}><meta name="Description"${add_attribute("content", `Get in touch with ${SITE_TITLE}.`, 0)}><meta property="og:description"${add_attribute("content", `Get in touch with ${SITE_TITLE}.`, 0)}><meta property="og:image"${add_attribute("content", DEFAULT_OG_IMAGE, 0)}><meta name="twitter:card" content="summary"><meta name="twitter:title"${add_attribute("content", `${SITE_TITLE} - Contact Us`, 0)}><meta name="twitter:description"${add_attribute("content", `Get in touch with ${SITE_TITLE}.`, 0)}><meta name="twitter:image"${add_attribute("content", DEFAULT_OG_IMAGE, 0)}><!-- HEAD_svelte-286kb8_END -->`, ""} <div class="flex flex-col items-center justify-center max-w-7xl mx-auto lg:px-8 "><div class="flex flex-col lg:flex-row w-full px-4 py-16 border-gray-200 dark:border-gray-700 sm:px-8"> <div class="lg:w-1/2 lg:pr-8 bg-primary p-8 text-white" data-svelte-h="svelte-1tv5b5o"><h1 class="font-medium lowercases pb-10 text-5xl leading-none md:text-6xl lg:text-6xl">contact us.</h1> <h2 class="max-w-xl pb-10 text-xl leading-9 text-colorary">Reach out to Zngweb | Transformative Web Development. We&#39;re here to assist you!</h2></div>  <div class="lg:w-1/2 p-8 "><div class="text-center" data-svelte-h="svelte-1h8alm9"><h2 class="text-4xl md:text-5xl font-medium "><span class="relative inline-block ml-2 before:absolute before:-inset-1 before:block before:-skew-y-3 before:bg-red-500"><span class="relative text-white skew-y-3">get in</span></span> touch.</h2> <p class="pb-10 text-xl leading-9 text-colorary">Have questions or want to discuss a project? Drop us a message below!</p></div>   <div class="max-w-3xl mx-auto"> <form id="contactform" name="contact" method="POST" data-netlify="true" data-svelte-h="svelte-4r98e1"><p><label>Your Name: <input type="text" name="name"></label></p> <p><label>Your Email: <input type="email" name="email"></label></p> <p><label>Message: <textarea name="message"></textarea></label></p> <p><button class="mx-2 bg-red-50 border-2 px-2 rounded-md block mx-auto" type="submit">Send</button></p> <br> <input type="hidden" name="form-name" value="contact"></form></div></div></div></div>`;
});
export {
  Page as default
};
